const actionTypes = {
    FETCH_PROMPT_REQUEST: "FETCH_PROMPT_REQUEST",
    FETCH_PROMPT_SUCCESS: "FETCH_PROMPT_SUCCESS",
    FETCH_PROMPT_FAILURE: "FETCH_PROMPT_FAILURE",

    POST_RHYME_REQUEST: "POST_RHYME_REQUEST",
    POST_RHYME_SUCCESS: "POST_RHYME_SUCCESS",
    POST_RHYME_FAILURE: "POST_RHYME_REQUEST",

    ANALYSED_FILTER: "ANALYSED_FILTER",
    ANALYSED_OPTIONS_COLOR: "ANALYSED_OPTIONS_COLOR",
    ANALYSED_OPTIONS_ALL: "ANALYSED_OPTIONS_ALL"
}

export default actionTypes